name: mirror-eval
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - datasets
  - dynaconf
  - jinja2
  - huggingface-hub
  - transformers
  - numpy
  - torch
  - pytest
  - black
  - flake8
  - pip:
    - -e .
    - torch==2.8.0+cu129
