# General settings for benchmarks
[benchmarks]
# benchmarks: which benchmarks to run, by name
benchmarks = [
    "creativity"
]

[slurm_job]
use_slurm = false
job_name = "test_job"
time = "01:00:00"
ntasks = 1
nodes = 1
mem_per_cpu = "16G"
gpus = 1
conda_env = "mirror-eval"
qos = ""

[creativity]
metrics = [
    "llm-as-a-judge",
    "self-avgcosine",
    "chamfer"
]
datasets = [
    "royal42/gcr-diversity",
    "royal42/mt-eval-creativity-demo"    
]
llm_judge_models = [
    "Qwen/Qwen1.5-0.5B-Chat"
    # "meta-llama/Llama-3.3-70B-Instruct",
    # "meta-llama/Meta-Llama-3.1-8B-Instruct",
    # "google/gemma-7b-it",
    # "Qwen/Qwen3-30B-A3B-Instruct-2507"
]
other_models = [
    "FacebookAI/roberta-large"
]
output_dir = "./results/testing"
