[model]
model_checkpoint_path = "Qwen/Qwen3-0.6B"

# General settings for benchmarks
[benchmarks]
# benchmarks: which benchmarks to run, by name
benchmarks = [
    "mta"
]

[slurm_job]
use_slurm = false
job_name = "test_job"
time = "01:00:00"
ntasks = 1
nodes = 1
mem_per_cpu = "16G"
gpus = 1
conda_env = "mirror-eval"
qos = ""

[mta]
metrics = [
    "llm-as-a-judge"
]
datasets = [
    "royal42/mta-test"
]
llm_judge_model = "Qwen/Qwen1.5-0.5B-Chat"
judge_prompt_name = "scale"
output_dir = ""

