[slurm_job]
use_slurm = true
job_name = "test_job"
time = "01:00:00"
ntasks = 1
nodes = 1
mem_per_cpu = "16G"
gpus = 1
conda_env = "mirror-eval"
qos = ""

[creativity]
models = [
    "meta-llama/Llama-3.3-70B-Instruct"
    "meta-llama/Meta-Llama-3.1-8B-Instruct",
    "google/gemma-7b-it",
    "Qwen/Qwen3-30B-A3B-Instruct-2507"
]
